const dashboardEquipments = {
  aiCameras: {
    id: "",
    img: "",
    title: "",
    count: "",
    category: "",
    list: [
      {
        id: "AI-Cam1",
        category: "aiCameras",
        title: "AI Camera #1",
        area: "Construction Area, Zone 1",
        connectivityPercentage: "79%",
        incidentsObservation: "32 min ago",
        operationAlertObservation: "3 days ago",
        motionObservation: "5 sec ago",
        timeStamp: "12-15-2022 | 09:00 AM",
        location: {
          lat: 39.95479636747346,
          lng: -75.19125340481472,
        },
      },
      {
        id: "AI-Cam2",
        category: "aiCameras",
        title: "AI Camera #2",
        area: "Construction Area, Zone 1",
        connectivityPercentage: "79%",
        incidentsObservation: "32 min ago",
        operationAlertObservation: "3 days ago",
        motionObservation: "5 sec ago",
        timeStamp: "12-15-2022 | 09:00 AM",
        location: {
          lat: 39.95465062495,
          lng: -75.19156122272521,
        },
      },
    ],
  },
  envrSensors: {
    id: "",
    img: "",
    title: "",
    count: "",
    category: "",
    list: [
      {
        id: "AI-Cam1",
        category: "envrSensors",
        title: "Envr Sensors #1",
        area: "Construction Area, Zone 1",
        connectivityPercentage: "79%",
        incidentsObservation: "32 min ago",
        operationAlertObservation: "3 days ago",
        motionObservation: "5 sec ago",
        timeStamp: "12-15-2022 | 09:00 AM",
        location: {
          lat: 39.9546330296282,
          lng: -75.19113445372379,
        },
      },
      {
        id: "AI-Cam2",
        category: "envrSensors",
        title: "Envr Sensors #2",
        area: "Construction Area, Zone 1",
        connectivityPercentage: "79%",
        incidentsObservation: "32 min ago",
        operationAlertObservation: "3 days ago",
        motionObservation: "5 sec ago",
        timeStamp: "12-15-2022 | 09:00 AM",
        location: {
          lat: 39.95467066644549,
          lng: -75.19144746835305,
        },
      },
    ],
  },
  floodSensors: {
    id: "",
    img: "",
    title: "",
    count: "",
    category: "",
    list: [
      {
        id: "AI-Cam1",
        category: "floodSensors",
        title: "Flood Sensor #1",
        area: "Construction Area, Zone 1",
        connectivityPercentage: "79%",
        incidentsObservation: "32 min ago",
        operationAlertObservation: "3 days ago",
        motionObservation: "5 sec ago",
        timeStamp: "12-15-2022 | 09:00 AM",
        location: {
          lat: 39.95446073977229,
          lng: -75.19156782580588,
        },
      },
      {
        id: "AI-Cam2",
        category: "floodSensors",
        title: "Flood Sensor #2",
        area: "Construction Area, Zone 1",
        connectivityPercentage: "79%",
        incidentsObservation: "32 min ago",
        operationAlertObservation: "3 days ago",
        motionObservation: "5 sec ago",
        timeStamp: "12-15-2022 | 09:00 AM",
        location: {
          lat: 39.95435610583542,
          lng: -75.19096305748663,
        },
      },
    ],
  },
};

export default dashboardEquipments;
