export default {
  title: "Hello Infinite English",
  profile: "Profile English",
  hello: "Hello",
  changeLang: "Change Language",
  changeTheme: "Change Theme",
  equipment: "Equipment",
  aiCameras: "AI Cameras",
  envrSensor: "Envr. Sensor",
  floodSensor: "Floor Sensor",
  search: "Search",
  noResult: "No Result Found",
  grokEye: "Grok Eye",
  raiseAlert: "Raise Alert",
  call: "Call",
  connectivity: "Connectivity or Celluar",
  incidents: "Incidents",
  operationAlert: "Operation Alert",
  motion: "Motion",
  logout: "Logout",
  dashboard: "Dashboard",
  alerts: "Alerts",
  poweredBy: "Powered by",
  copyRight: "© 2023. All Rights Reserved",
};
