export default {
  title: "Hello Infinite Italian",
  profile: "Profile Italian",
  hello: "Hola",
  changeLang: "Change Language",
  changeTheme: "Change Theme",
  equipment: "Attrezzatura",
  aiCameras: "Telecamere AI",
  envrSensor: "Env. Sensore",
  floodSensor: "Pavimento Sensore",
  search: "Ricerca",
  noResult: "Nessun Risultato Frovato",
  grokEye: "Grok Occhio",
  raiseAlert: "Alza l'allerta",
  call: "Chiamata",
  connectivity: "Connettività o Cellulare",
  incidents: "Incidenti",
  operationAlert: "Avviso Operativo",
  motion: "Movimento",
  logout: "Disconnettersi",
  dashboard: "Pannello Di Controllo",
  alerts: "Avvisi",
};
