export default {
  title: "Hello Infinite Italian",
  profile: "Profile Italian",
  hello: "Hola",
  changeLang: "Change Language",
  changeTheme: "Change Theme",
  dashboardListName: "Attrezzatura",
  tabsListName1: "Telecamere AI",
  tabsListName2: "Env. Sensore",
  tabsListName3: "Pavimento Sensore",
  search: "Ricerca",
  noResult: "Nessun Risultato Frovato",
  listIconName1: "Grok Occhio",
  listIconName2: "Alza l'allerta",
  listIconName3: "Chiamata",
  listItemConnectivityText: "Connettività o Cellulare",
  listItemIconArrayName1: "Incidenti",
  listItemIconArrayName2: "Avviso Operativo",
  listItemIconArrayName3: "Movimento",
};
