import colorCodes from "./colors";

let theme = {
  defaultTheme: {
    palette: {
      login: {
        pageBackgroundColor: "#300254",
        loginBtnColor: "",
        titleColor: "",
        forgotPwdColor: "",
        loginBannerTitle: colorCodes.colorWhite,
        loginFormBg: colorCodes.colorWhite,
        loginBannerDescription: colorCodes.colorWhite,
        welcomeContent: colorCodes.welcomeContent,
        loginFormTitle: colorCodes.loginFormTitle,
        inputTitleColor: colorCodes.inputTitleColor,
        inputPlaceholder: colorCodes.inputPlaceholder,
        copyRight: colorCodes.darkBlack1,
        loginButton: colorCodes.blue,
        atthirate: colorCodes.lightBlue,
        logoBg: colorCodes.logoBg,
      },
      dashboard: {
        white: colorCodes.colorWhite,
        whiteGrayShade: colorCodes.whiteGrayShade,
        lightGrey2: colorCodes.lightGrey2,
        lightBlue4: colorCodes.lightBlue4,
        grayShade3: colorCodes.grayShade3,
        black: colorCodes.blackColor,
        darkBlueBlackShade: colorCodes.darkBlueBlackShade,
        darkGreenShade: colorCodes.darkGreenShade,
        lightGrayWhiteShade: colorCodes.lightGrayWhiteShade,
        blueGrayNewShade: colorCodes.blueGrayNewShade,
        darkBlueGrayShade: colorCodes.darkBlueGrayShade,
        paleGreenShade: colorCodes.paleGreenShade,
        lightBlueGrayShade: colorCodes.lightBlueGrayShade,
        darkBlueBlackShade2: colorCodes.darkBlueBlackShade2,
        lightGrey: colorCodes.lightGrey,
        skyBlueColor: colorCodes.skyBlueColor,
        darkRedColor: colorCodes.darkRedColor,
        goldenOrangeColor: colorCodes.goldenOrangeColor,
        lightGrayShade5: colorCodes.lightGrayShade5,
        grayShade: colorCodes.grayShade,
        blackGrayWhite: colorCodes.blackGrayWhite,
      },
      header: {
        headerBg: colorCodes.headerBg,
        white: colorCodes.colorWhite,
        lightGrayWhiteShade: colorCodes.lightGrayWhiteShade,
        darkGreenShade2: colorCodes.darkGreenShade2,
        darkGreenShade: colorCodes.darkGreenShade,
      },
      footer: {
        footerBg: colorCodes.footerBg,
      },
    },
    spacing: 5,
    typography: { fontFamily: "Arial" },
  },
  greenTheme: {
    palette: {
      login: {
        pageBackgroundColor: "#68F73A",
        loginBtnColor: "",
        titleColor: "",
        forgotPwdColor: "",
        loginBannerTitle: colorCodes.colorWhite,
        loginFormBg: colorCodes.colorWhite,
        loginBannerDescription: colorCodes.colorWhite,
        welcomeContent: colorCodes.welcomeContent,
        loginFormTitle: colorCodes.loginFormTitle,
        inputTitleColor: colorCodes.inputTitleColor,
        inputPlaceholder: colorCodes.inputPlaceholder,
        copyRight: colorCodes.darkBlack1,
        loginButton: colorCodes.blue,
        atthirate: colorCodes.lightBlue,
        logoBg: colorCodes.logoBg,
      },
      dashboard: {
        white: colorCodes.colorWhite,
        whiteGrayShade: colorCodes.whiteGrayShade,
        lightGrey2: colorCodes.lightGrey2,
        lightBlue4: colorCodes.lightBlue4,
        grayShade3: colorCodes.grayShade3,
        black: colorCodes.blackColor,
        darkBlueBlackShade: colorCodes.darkBlueBlackShade,
        darkGreenShade: colorCodes.darkGreenShade,
        lightGrayWhiteShade: colorCodes.lightGrayWhiteShade,
        blueGrayNewShade: colorCodes.blueGrayNewShade,
        darkBlueGrayShade: colorCodes.darkBlueGrayShade,
        paleGreenShade: colorCodes.paleGreenShade,
        lightBlueGrayShade: colorCodes.lightBlueGrayShade,
        darkBlueBlackShade2: colorCodes.darkBlueBlackShade2,
        lightGrey: colorCodes.lightGrey,
        skyBlueColor: colorCodes.skyBlueColor,
        darkRedColor: colorCodes.darkRedColor,
        goldenOrangeColor: colorCodes.goldenOrangeColor,
        lightGrayShade5: colorCodes.lightGrayShade5,
        grayShade: colorCodes.grayShade,
        blackGrayWhite: colorCodes.blackGrayWhite,
      },
      header: {
        headerBg: colorCodes.headerBg,
        white: colorCodes.colorWhite,
        lightGrayWhiteShade: colorCodes.lightGrayWhiteShade,
        darkGreenShade2: colorCodes.darkGreenShade2,
        darkGreenShade: colorCodes.darkGreenShade,
      },
      footer: {
        footerBg: colorCodes.footerBg,
      },
    },
    spacing: 5,
    typography: { fontFamily: "Arial" },
  },
  yellowTheme: {
    palette: {
      login: {
        pageBackgroundColor: "#D1F557",
        loginBtnColor: "",
        titleColor: "",
        forgotPwdColor: "",
        loginBannerTitle: colorCodes.colorBlack,
        loginFormBg: colorCodes.colorWhite,
        loginBannerDescription: colorCodes.colorWhite,
        welcomeContent: colorCodes.welcomeContent,
        loginFormTitle: colorCodes.loginFormTitle,
        inputTitleColor: colorCodes.inputTitleColor,
        inputPlaceholder: colorCodes.inputPlaceholder,
        copyRight: colorCodes.darkBlack1,
        loginButton: colorCodes.blue,
        atthirate: colorCodes.lightBlue,
        logoBg: colorCodes.logoBg,
      },
      dashboard: {
        white: colorCodes.colorWhite,
        whiteGrayShade: colorCodes.whiteGrayShade,
        lightGrey2: colorCodes.lightGrey2,
        lightBlue4: colorCodes.lightBlue4,
        grayShade3: colorCodes.grayShade3,
        black: colorCodes.blackColor,
        darkBlueBlackShade: colorCodes.darkBlueBlackShade,
        darkGreenShade: colorCodes.darkGreenShade,
        lightGrayWhiteShade: colorCodes.lightGrayWhiteShade,
        blueGrayNewShade: colorCodes.blueGrayNewShade,
        darkBlueGrayShade: colorCodes.darkBlueGrayShade,
        paleGreenShade: colorCodes.paleGreenShade,
        lightBlueGrayShade: colorCodes.lightBlueGrayShade,
        darkBlueBlackShade2: colorCodes.darkBlueBlackShade2,
        lightGrey: colorCodes.lightGrey,
        skyBlueColor: colorCodes.skyBlueColor,
        darkRedColor: colorCodes.darkRedColor,
        goldenOrangeColor: colorCodes.goldenOrangeColor,
        lightGrayShade5: colorCodes.lightGrayShade5,
        grayShade: colorCodes.grayShade,
        blackGrayWhite: colorCodes.blackGrayWhite,
      },
      header: {
        headerBg: colorCodes.headerBg,
        white: colorCodes.colorWhite,
        lightGrayWhiteShade: colorCodes.lightGrayWhiteShade,
        darkGreenShade2: colorCodes.darkGreenShade2,
        darkGreenShade: colorCodes.darkGreenShade,
      },
      footer: {
        footerBg: colorCodes.footerBg,
      },
    },
    spacing: 5,
    typography: { fontFamily: "Arial" },
  },
  redTheme: {
    palette: {
      login: {
        pageBackgroundColor: "#C10132",
        loginBtnColor: "",
        titleColor: "",
        forgotPwdColor: "",
        loginBannerTitle: colorCodes.colorBlack,
        loginFormBg: colorCodes.colorWhite,
        loginBannerDescription: colorCodes.colorWhite,
        welcomeContent: colorCodes.welcomeContent,
        loginFormTitle: colorCodes.loginFormTitle,
        inputTitleColor: colorCodes.inputTitleColor,
        inputPlaceholder: colorCodes.inputPlaceholder,
        copyRight: colorCodes.darkBlack1,
        loginButton: colorCodes.blue,
        atthirate: colorCodes.lightBlue,
        logoBg: colorCodes.logoBg,
      },
      dashboard: {
        white: colorCodes.colorWhite,
        whiteGrayShade: colorCodes.whiteGrayShade,
        lightGrey2: colorCodes.lightGrey2,
        lightBlue4: colorCodes.lightBlue4,
        grayShade3: colorCodes.grayShade3,
        black: colorCodes.blackColor,
        darkBlueBlackShade: colorCodes.darkBlueBlackShade,
        darkGreenShade: colorCodes.darkGreenShade,
        lightGrayWhiteShade: colorCodes.lightGrayWhiteShade,
        blueGrayNewShade: colorCodes.blueGrayNewShade,
        darkBlueGrayShade: colorCodes.darkBlueGrayShade,
        paleGreenShade: colorCodes.paleGreenShade,
        lightBlueGrayShade: colorCodes.lightBlueGrayShade,
        darkBlueBlackShade2: colorCodes.darkBlueBlackShade2,
        lightGrey: colorCodes.lightGrey,
        skyBlueColor: colorCodes.skyBlueColor,
        darkRedColor: colorCodes.darkRedColor,
        goldenOrangeColor: colorCodes.goldenOrangeColor,
        lightGrayShade5: colorCodes.lightGrayShade5,
        grayShade: colorCodes.grayShade,
        blackGrayWhite: colorCodes.blackGrayWhite,
      },
      header: {
        headerBg: colorCodes.headerBg,
        white: colorCodes.colorWhite,
        lightGrayWhiteShade: colorCodes.lightGrayWhiteShade,
        darkGreenShade2: colorCodes.darkGreenShade2,
        darkGreenShade: colorCodes.darkGreenShade,
      },
      footer: {
        footerBg: colorCodes.footerBg,
      },
    },
    spacing: 5,
    typography: { fontFamily: "Arial" },
  },
};

export default theme;
